id: yoshi_policy
name: Yoshi Policies
description: All of the things
owner: beckwith@google.com

for: repositories
where:
  - resource.visibility.public

ensure:
  files:
    - 'README.md'
    - 'CODE_OF_CONDUCT.md'
